feat(ci): Run updates at PR level instead of after merge (#9389)
Run updates at PR level instead of after merge

Co-authored-by: chrismallinson <chrismallinson@users.noreply.github.com>

diff --git a/.github/actions/auto-update-seed/action.yaml b/.github/actions/auto-update-seed/action.yaml
--- a/.github/actions/auto-update-seed/action.yaml
+++ b/.github/actions/auto-update-seed/action.yaml
@@ -25,6 +25,12 @@ inputs:
     description: "Whether to skip caching and always regenerate"
     required: false
     default: "true"
+  create-artifacts:
+    description: "Whether or not to create artifacts for the seed changes"
+    required: true
+  create-pr:
+    description: "Whether or not to create a PR with changes"
+    required: true
   secret-fern-github-pat:
     description: "GitHub Access Token for Fern"
     required: true
@@ -35,6 +41,14 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: Validate update options
+      shell: bash
+      run: |
+        if [[ "${{ inputs.create-artifacts }}" == "${{ inputs.create-pr }}" ]]; then
+          echo "Invalid seed update settings. One and only one update method must be enabled."
+          exit 1
+        fi
+
     - name: Run seed
       uses: ./.github/actions/cached-seed
       with:
@@ -45,7 +59,41 @@ runs:
         skip-scripts: ${{ inputs.skip-scripts }}
         cache-disabled: ${{ inputs.cache-disabled }}
 
+    # Add changes first to simplify git diff checks, no changes will NOT error here
+    - name: Check for changes
+      if: inputs.create-artifacts == 'true'
+      id: check-changes
+      shell: bash
+      run: |
+        git add seed/${{ inputs.generator-name }}/*
+        if git --no-pager diff --staged --exit-code; then
+          echo "No changes detected for seed."
+          echo "seed-changes-generated=false" >> $GITHUB_OUTPUT
+        else
+          echo "Changes detected for seed."
+          echo "seed-changes-generated=true" >> $GITHUB_OUTPUT
+        fi
+
+    # Make patch file for seed changes
+    - name: Make Patch for Seed Artifacts
+      if: steps.check-changes.outputs.seed-changes-generated == 'true' && inputs.create-artifacts == 'true'
+      shell: bash
+      run: |
+        git diff --staged > seed-${{ inputs.generator-name }}.patch
+
+    # Upload patch files as artifacts to be applied and committed by caller when all of seed is up to date
+    - name: Upload Seed Artifacts
+      if: steps.check-changes.outputs.seed-changes-generated == 'true' && inputs.create-artifacts == 'true'
+      uses: actions/upload-artifact@v4
+      with:
+        name: seed-${{ inputs.generator-name }}.patch
+        path: seed-${{ inputs.generator-name }}.patch
+        if-no-files-found: error
+        retention-days: 7
+
+    # Create PR, approve and set to merge all at generator level
     - name: Create Pull Request
+      if: steps.check-changes.outputs.seed-changes-generated == 'true' && inputs.create-pr == 'true'
       id: cpr
       uses: peter-evans/create-pull-request@v5
       with:
@@ -60,19 +108,19 @@ runs:
           language/${{ inputs.language-name }}
 
     - name: Log PR Creation Failure
-      if: steps.cpr.outputs.pull-request-operation != 'created'
+      if: steps.cpr.outputs.pull-request-operation != 'created' && inputs.create-pr  == 'true'
       shell: bash
       run: |
         echo "PR was not created, likely due to no diff for the generated seed output"
 
     - name: Log PR Creation Details
-      if: steps.cpr.outputs.pull-request-operation == 'created'
+      if: steps.cpr.outputs.pull-request-operation == 'created' && inputs.create-pr  == 'true'
       shell: bash
       run: |
         echo "PR Created: ${{ steps.cpr.outputs.pull-request-url }}"
 
     - name: Enable Pull Request Automerge
-      if: steps.cpr.outputs.pull-request-operation == 'created'
+      if: steps.cpr.outputs.pull-request-operation == 'created' && inputs.create-pr  == 'true'
       uses: peter-evans/enable-pull-request-automerge@v3
       with:
         token: ${{ inputs.secret-fern-github-pat }}
@@ -80,7 +128,7 @@ runs:
         merge-method: squash
 
     - name: Approve PR
-      if: steps.cpr.outputs.pull-request-operation == 'created'
+      if: steps.cpr.outputs.pull-request-operation == 'created' && inputs.create-pr  == 'true'
       uses: ./.github/actions/auto-approve
       with:
         approver-gh-token: ${{ inputs.secret-pr-bot-gh-pat }}
