add logic for looking at specific checks

diff --git a/.github/actions/auto-approve/action.yaml b/.github/actions/auto-approve/action.yaml
--- a/.github/actions/auto-approve/action.yaml
+++ b/.github/actions/auto-approve/action.yaml
@@ -12,20 +12,43 @@ inputs:
     description: Require checks to pass before approving PR
     required: false
     default: 'false'
+  enforced-checks:
+    description: List of checks to enforce (provided as a comma separated list)
+    type: string
+    default: ''
+
 runs:
   using: "composite"
   steps:
     - name: Check status
-      if: inputs.enforce-checks == 'true'
+      if: inputs.enforce-checks == 'true' && inputs.enforced-checks == ''
       shell: bash
       env:
         GH_TOKEN: ${{ inputs.approver-gh-token }}
       run: |
-        echo "Waiting for jobs to finish running"
-        while echo $(gh pr checks ${{ inputs.pull-request-number }}) | grep -q 'pending'; do echo "job still running"; sleep 30s; done
+        echo "Waiting for all checks to finish running"
+        while echo $(gh pr checks ${{ inputs.pull-request-number }}) | grep -q 'pending'; do echo "$(gh pr checks 63 | grep pending | wc -l) check(s) still running"; sleep 30s; done
 
-        echo "Jobs done, checking for failures"
-        if echo $(gh pr checks ${{ inputs.pull-request-number }}) | grep -q 'fail'; then echo "PR CI Failed"; exit 1; else echo "PR CI Succeeded"; fi
+        echo "All checks done running, looking for failures"
+        if echo $(gh pr checks ${{ inputs.pull-request-number }}) | grep -q 'fail'; then echo "Some/All Checks Failed"; exit 1; else echo "All Checks Passed"; fi
+
+        echo "PR Ready for approval"
+
+    - name: Specific PR check status
+      if: inputs.enforce-checks == 'true' && inputs.enforced-checks != ''
+      shell: bash
+      env:
+        GH_TOKEN: ${{ inputs.approver-gh-token }}
+      run: |
+        echo "Specifically checking status of: '${{ inputs.enforced-checks }}' checks"
+        for i in $(echo ${{ inputs.enforced-checks }} | sed "s/,/ /g")
+        do
+            echo "Waiting for '$i' check to finish running"
+            while echo $(gh pr checks ${{ inputs.pull-request-number }}) | grep '$i' | grep -q 'pending'; do echo "$i check still running"; sleep 15s; done
+
+            echo "Checking status of '$i'"
+            if echo $(gh pr checks ${{ inputs.pull-request-number }}) | grep '$i' | grep -q 'fail'; then echo "'$i' Failed"; exit 1; else echo "'$i' Succeeded"; fi
+        done
 
         echo "PR Ready for approval"
 
