improve logging and flow

diff --git a/.github/workflows/check-links.yml b/.github/workflows/check-links.yml
--- a/.github/workflows/check-links.yml
+++ b/.github/workflows/check-links.yml
@@ -25,9 +25,44 @@ jobs:
       - name: Create config
         run: echo -e "[csv]\nseparator=,\n[output]\nignoreerrors=\n  ^http ^403 Forbidden" > lcconfig
       - name: Check ${{ matrix.site.name }} Links
-        run: linkchecker https://${{ matrix.site.url }} --check-extern --no-status --no-warnings --config lcconfig -F csv/utf-8/link_report.csv
-      - name: Postprocess report
-        run: python postprocess_report.py
+        run: |
+          set +e
+          linkchecker https://${{ matrix.site.url }} --check-extern --no-status --no-warnings --config lcconfig -F csv/utf-8/link_report.csv
+
+          if [ $? -ne 0 ]; then
+            echo "Bad links found. Please see report."
+          else
+            echo "Check completed. No issues found."
+            exit 0
+          fi
+
+          echo "Scan done, generating summary"
+
+          started=false
+          while read p; do
+            let "ln++"
+            # skip comments (top and bottom)
+            if [[ $p == \#* ]]; then
+              continue
+            fi
+            # make sure first line after comments is skipped
+            if [[ "$started" = false ]]; then
+              started=true
+              continue
+            fi
+            
+            IFS=',' read -r -a array <<< "$p"
+
+            if [[ ${array[10]} == '' ]]; then
+              echo "::error::URL: ${array[0]} on page:${array[1]} is returning a ${array[3]}"
+            else
+              echo "::error::URL: ${array[0]} linked from '${array[10]}' on page:${array[1]} is returning a ${array[3]}"
+            fi
+
+          done < link_report.csv
+
+          exit 1
+
       - name: Upload report
         if: failure()
         uses: actions/upload-artifact@v4
