Anotha one

diff --git a/.github/workflows/nightly-seed-grouping.yml b/.github/workflows/nightly-seed-grouping.yml
--- a/.github/workflows/nightly-seed-grouping.yml
+++ b/.github/workflows/nightly-seed-grouping.yml
@@ -180,6 +180,16 @@ jobs:
           pattern: "*-seed-groups.json"
           merge-multiple: true
 
+      - name: Check for Seed Group Files
+        shell: bash
+        run: |
+          file_count=$(find ./artifacts -type f -name "*.patch" | wc -l)
+          echo "Number of patches downloaded: $file_count"
+          if [ "$file_count" -eq 0 ]; then
+            echo "Error: No seed group files found"
+            exit 1
+          fi
+
       - name: Check and Make Directory
         run: |
           if [ ! -d ".github/workflow-resource-files/seed-groups" ]; then
@@ -188,25 +198,20 @@ jobs:
 
       - name: Overwrite Repo Seed Group Files
         run: |
-          if [ -f artifacts/*-seed-groups.json ]; then
-            cp -f artifacts/*-seed-groups.json .github/workflow-resource-files/seed-groups/
-          else
-            echo "Warning: No seed group files found"
-          fi
+          cp -f artifacts/*-seed-groups.json .github/workflow-resource-files/seed-groups/
 
       # Setup our linting tools
       - name: Install and Setup Dev Env
         uses: ./.github/actions/install
 
-        #  CHRISM -temp
-      # - name: Lint the Seed Group Files
-      #   run: |
-      #     if [ -f .github/workflow-resource-files/seed-groups/*-seed-groups.json ]; then
-      #       pnpm format:fix .github/workflow-resource-files/seed-groups/
-      #     else
-      #       echo "Error: No seed group files found"
-      #       exit 1
-      #     fi
+      - name: Lint the Seed Group Files
+        run: |
+          if [ -f .github/workflow-resource-files/seed-groups/*-seed-groups.json ]; then
+            pnpm format:fix .github/workflow-resource-files/seed-groups/
+          else
+            echo "Error: No seed group files found"
+            exit 1
+          fi
 
       # Create PR, approve and set to merge per generator
       - name: Create Pull Request
@@ -245,7 +250,7 @@ jobs:
         shell: bash
         run: |
           echo "PR was not created or updated, likely due to no diff for seed group files"
-          echo "PR Operation: ${{ steps.cpr.outputs.pull-request-operation }}"
+          echo "PR Operation: ${{ steps.cpr.outputs.pull-request-operation }}. Note: if operation is blank then there were no changes and create-pull-request GitHub Action exited silently and early."
 
       #  CHRISM - add back
       # - name: Enable Pull Request Automerge
