Forcing fiailure for test

diff --git a/.github/workflows/nightly-seed-grouping.yml b/.github/workflows/nightly-seed-grouping.yml
--- a/.github/workflows/nightly-seed-grouping.yml
+++ b/.github/workflows/nightly-seed-grouping.yml
@@ -129,6 +129,12 @@ jobs:
             rust-sdk,
           ]
     steps:
+      - name: Force failure test
+        shell: bash
+        run: |
+          echo "Error: Force failure test"
+          exit 1
+
       - name: Make artifacts directory
         shell: bash
         run: |
@@ -200,10 +206,11 @@ jobs:
 
       - name: Lint the Seed Group Files
         run: |
-          if [ -f artifacts/*-seed-groups.json ]; then
-            pnpm format:fix ./.github/workflow-resource-files/seed-groups/
+          if [ -f .github/workflow-resource-files/seed-groups/*-seed-groups.json ]; then
+            pnpm format:fix .github/workflow-resource-files/seed-groups/
           else
-            echo "Warning: No seed group files found"
+            echo "Error: No seed group files found"
+            exit 1
           fi
 
       # Create PR, approve and set to merge per generator
