add retry
attempting to implement solution described here: https://github.com/orgs/community/discussions/67654

diff --git a/.github/workflows/seed.yml b/.github/workflows/seed.yml
--- a/.github/workflows/seed.yml
+++ b/.github/workflows/seed.yml
@@ -97,6 +97,18 @@ jobs:
               - 'generators/php/**'
               - 'seed/php-sdk/**'
               - 'seed/php-model/**'
+      - name: test-step
+        id: autofail
+        run: exit 1
+      - name: retry-on-failure
+        #if: failure() && steps.filter.outcome == 'failure' && fromJSON(github.run_attempt) < 3
+        if: failure() && steps.autofail.outcome == 'failure' && fromJSON(github.run_attempt) < 3
+        env:
+          GH_REPO: ${{ github.repository }}
+          GH_TOKEN: ${{ github.token }}
+          GH_DEBUG: api
+        run: gh workflow run rerun.yml -F run_id=${{ github.run_id }}
+        
   ruby-model:
     runs-on: Seed
     needs: changes
