feat(seed): Add GitHub workflow caching

diff --git a/.github/workflows/seed.yml b/.github/workflows/seed.yml
--- a/.github/workflows/seed.yml
+++ b/.github/workflows/seed.yml
@@ -37,7 +37,6 @@ jobs:
             seed: 
               - '.github/workflows/seed.yml'
               - 'packages/seed/**'
-              - 'test-definitions/**'
               - 'packages/ir-sdk/fern/apis/**'
               - 'packages/cli/generation/ir-generator/**'
             ruby: 
@@ -540,28 +539,72 @@ jobs:
       - name: Checkout repo
         uses: actions/checkout@v4
 
+      - name: Generate input hash
+        id: hash
+        run: |
+          HASH=$(./scripts/hash.sh \
+            packages/seed \
+            test-definitions \
+            packages/ir-sdk/fern/apis \
+            packages/cli/generation/ir-generator \
+            generators/go \
+            seed/go-sdk \
+            --exclude versions.yml)
+          echo "hash=${HASH}" >> $GITHUB_OUTPUT
+
+      - name: Check cache
+        id: cache
+        uses: actions/cache@v3
+        with:
+          path: |
+            seed/go-sdk/
+          key: seed-go-sdk-${{ steps.hash.outputs.hash }}
+          lookup-only: true  # Don't save to the cache until we know it's successful.
+
       - name: Install
+        if: steps.cache.outputs.cache-hit != 'true'
         uses: ./.github/actions/install
 
       - uses: bufbuild/buf-setup-action@v1.34.0
+        if: steps.cache.outputs.cache-hit != 'true'
         with:
           github_token: ${{ github.token }}
 
       - uses: actions/setup-go@v5
+        if: steps.cache.outputs.cache-hit != 'true'
         with:
           go-version: "stable"
 
       - name: Install protoc-gen-openapi
+        if: steps.cache.outputs.cache-hit != 'true'
         run: go install github.com/google/gnostic/cmd/protoc-gen-openapi@v0.7.0
 
       - name: Seed Test
+        if: steps.cache.outputs.cache-hit != 'true'
         env:
           FORCE_COLOR: "2"
         run: |
           pnpm seed:local test --generator go-sdk --parallel 16
 
       - name: Ensure no changes to git-tracked files
-        run: git --no-pager diff --exit-code  -- ":(exclude)seed/*/.mock/*"
+        id: validate
+        if: steps.cache.outputs.cache-hit != 'true'
+        run: |
+          # Run git diff check
+          if git --no-pager diff --exit-code -- ":(exclude)seed/*/.mock/*"; then
+            echo "Results are valid, saving to cache"
+            echo "valid=true" >> $GITHUB_OUTPUT
+          else
+            echo "Changes detected in git-tracked files, not saving to cache"
+            exit 1  # Fail the workflow if changes detected
+          fi
+
+      - name: Save cache
+        if: steps.cache.outputs.cache-hit != 'true' && steps.validate.outputs.valid == 'true'
+        uses: actions/cache@v3
+        with:
+          path: seed/go-sdk
+          key: go-sdk-${{ steps.hash.outputs.hash }}
 
   csharp-model:
     runs-on: ubuntu-latest
